import { InventoryItem } from '@/types';

export const recipePerKgPlov: InventoryItem[] = [
  {
    id: 'rice',
    name: 'Rice',
    unit: 'kg',
    currentStock: 18,
    minimumStock: 8,
    recipeUsagePerKg: 0.35,
    category: 'base',
  },
  {
    id: 'meat',
    name: 'Meat',
    unit: 'kg',
    currentStock: 1.4,
    minimumStock: 6,
    recipeUsagePerKg: 0.25,
    category: 'protein',
  },
  {
    id: 'carrot',
    name: 'Carrot',
    unit: 'kg',
    currentStock: 9,
    minimumStock: 5,
    recipeUsagePerKg: 0.25,
    category: 'vegetable',
  },
  {
    id: 'oil',
    name: 'Oil',
    unit: 'L',
    currentStock: 2.2,
    minimumStock: 2,
    recipeUsagePerKg: 0.08,
    category: 'oil',
  },
  {
    id: 'onion',
    name: 'Onion',
    unit: 'kg',
    currentStock: 3.6,
    minimumStock: 2,
    recipeUsagePerKg: 0.05,
    category: 'vegetable',
  },
  {
    id: 'chickpeas',
    name: 'Chickpeas',
    unit: 'kg',
    currentStock: 1.1,
    minimumStock: 1.5,
    recipeUsagePerKg: 0.04,
    category: 'garnish',
  },
  {
    id: 'raisins',
    name: 'Raisins',
    unit: 'kg',
    currentStock: 0.9,
    minimumStock: 1,
    recipeUsagePerKg: 0.03,
    category: 'garnish',
  },
  {
    id: 'quail-eggs',
    name: 'Quail eggs',
    unit: 'pcs',
    currentStock: 52,
    minimumStock: 40,
    recipeUsagePerKg: 4,
    category: 'garnish',
  },
  {
    id: 'salt',
    name: 'Salt',
    unit: 'kg',
    currentStock: 1.8,
    minimumStock: 1,
    recipeUsagePerKg: 0.01,
    category: 'seasoning',
  },
  {
    id: 'spices',
    name: 'Spices',
    unit: 'kg',
    currentStock: 0.7,
    minimumStock: 0.7,
    recipeUsagePerKg: 0.01,
    category: 'seasoning',
  },
];
